remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: La Palma - AWESOME PAG ALERTS
description: "Repositório dedicado a colaboração quanto a construção e compartilhamento de queries usadas no Pagmon"